image: gitpod/workspace-full-vnc:latest

tasks:
  - command: |
      nvm install lts/gallium
      npm install -g npm
      npm install -g wrangler
      curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | sudo -E bash -s install deb-get
      deb-get update
      deb-get upgrade
      deb-get install google-chrome-stable discord

vscode:
  extensions:
    - zamerick.vscode-caddyfile-syntax
    - EditorConfig.EditorConfig
    - GitHub.github-vscode-theme
    - bierner.github-markdown-preview
    - bierner.markdown-checkbox
    - bierner.markdown-emoji
    - bierner.markdown-footnotes
    - bierner.markdown-mermaid
    - bierner.markdown-preview-github-styles
    - bierner.markdown-yaml-preamble
    - WakaTime.vscode-wakatime
    - timonwong.shellcheck
    - GitLab.gitlab-workflow
    - PKief.markdown-checkbox
    - PKief.material-icon-theme
    - PKief.material-product-icons
    - ms-python.python
    - rebornix.ruby
    - golang.go
    - DavidAnson.vscode-markdownlint
    - william-voyek.vscode-nginx
    - amazonwebservices.aws-toolkit-vscode
    - googlecloudtools.cloudcode
    - arcticicestudio.nord-visual-studio-code
    - stateful.stable
    - rangav.vscode-thunder-client
    - ms-azuretools.vscode-docker
    - mikestead.dotenv
    - Jannchie.codetime

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: true
