image: gitpod/workspace-full-vnc:latest

tasks:
  - command: |
      nvm install lts/fermium
      npm install -g npm
      npm install -g @cloudflare/wrangler

vscode:
  extensions:
    - bungcip.better-toml
    - zamerick.vscode-caddyfile-syntax
    - EditorConfig.EditorConfig
    - GitHub.vscode-pull-request-github
    - GitHub.github-vscode-theme
    - bierner.github-markdown-preview
    - bierner.markdown-checkbox
    - bierner.markdown-emoji
    - bierner.markdown-footnotes
    - bierner.markdown-mermaid
    - bierner.markdown-preview-github-styles
    - bierner.markdown-yaml-preamble
    - WakaTime.vscode-wakatime
    - timonwong.shellcheck
    - GitLab.gitlab-workflow
    - PKief.markdown-checkbox
    - PKief.material-icon-theme
    - PKief.material-product-icons
    - Equinusocio.vsc-community-material-theme
    - ms-python.python
    - rebornix.ruby
    - golang.go
    - silvenon.mdx
    - DavidAnson.vscode-markdownlint
    - william-voyek.vscode-nginx
    - abumalick.vscode-nvm
    - amazonwebservices.aws-toolkit-vscode
    - googlecloudtools.cloudcode
    - arcticicestudio.nord-visual-studio-code
    - stateful.stable
    - rangav.vscode-thunder-client
    - ms-vscode-remote.vscode-remote-extensionpack
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - ms-azuretools.vscode-docker
    - mikestead.dotenv
    - Jannchie.codetime

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: true
