image: gitpod/workspace-full-vnc:latest

tasks:
  - command: |
      nvm ls-remote --lts
      nvm ls
      nvm install lts/hydrogen
      npm install -g npm
      npm install -g wrangler
      curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | sudo -E bash -s install deb-get
      deb-get update
      deb-get upgrade
      deb-get install google-chrome-stable discord

vscode:
  extensions:
    - EditorConfig.EditorConfig
    - GitHub.github-vscode-theme
    - bierner.github-markdown-preview
    - bierner.markdown-checkbox
    - bierner.markdown-emoji
    - bierner.markdown-footnotes
    - bierner.markdown-mermaid
    - bierner.markdown-preview-github-styles
    - bierner.markdown-yaml-preamble
    - WakaTime.vscode-wakatime
    - timonwong.shellcheck
    - GitLab.gitlab-workflow
    - PKief.markdown-checkbox
    - PKief.material-icon-theme
    - PKief.material-product-icons
    - ms-python.python
    - golang.go
    - arcticicestudio.nord-visual-studio-code
    - rangav.vscode-thunder-client
    - ms-azuretools.vscode-docker
    - Jannchie.codetime

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: true
